name: CI
on:
  push:
    branches:
      - main

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: purcell/setup-emacs@master
        with:
          version: 28.1

      - name: checkout
        uses: actions/checkout@v3

      - name: pencil
        run: |
          chmod +x "${GITHUB_WORKSPACE}"/.github/make-readme.el
          "${GITHUB_WORKSPACE}"/.github/make-readme.el

      - name: add and commit
        uses: EndBug/add-and-commit@v9
        with:
          add: 'readme.org'
          committer_name: 'Github Actions'
          committer_email: 'github-actions[bot]@users.noreply.github.com'
          message: 'generate readme (automated)'
